version: "3"
services:
  app:
    image: app:latest
    container_name: go-intikom-app
    build:
      context: .
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./log:/log
    depends_on:
      postgres:
        condition: service_started
    restart: on-failure
  postgres:
    image: postgres:latest
    container_name: postgres_intikom
    environment:
      POSTGRES_DB: intikom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: