version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_intikom
    environment:
      POSTGRES_DB: intikom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: